-- MySQL Script generated by MySQL Workbench
-- Tue Jan  2 23:20:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Devathon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Devathon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Devathon` DEFAULT CHARACTER SET utf8 ;
USE `Devathon` ;

-- -----------------------------------------------------
-- Table `Devathon`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Devathon`.`Team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `stack_frontend` LONGTEXT NOT NULL,
  `stack_backend` LONGTEXT NOT NULL,
  `available_frontend_quota` INT NOT NULL DEFAULT 3,
  `available_backend_quota` INT NOT NULL DEFAULT 3,
  `edition` INT NOT NULL DEFAULT 6,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_by` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(45) NULL,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Devathon`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Devathon`.`Role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_by` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(45) NULL,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Devathon`.`Seniority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Devathon`.`Seniority` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_by` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(45) NULL,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Devathon`.`Developer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Devathon`.`Developer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` LONGTEXT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `github_link` VARCHAR(45) NOT NULL,
  `linkedin_link` VARCHAR(45) NOT NULL,
  `idrole` INT NOT NULL,
  `ceremony_available` TINYINT NOT NULL,
  `discord_username` VARCHAR(45) NOT NULL,
  `idseniority` INT NOT NULL,
  `looking_for_work` TINYINT NOT NULL,
  `retire_probability` TINYINT NOT NULL,
  `condition_accepted` TINYINT NOT NULL,
  `idteam` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_by` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(45) NULL,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idteam_idx` (`idteam` ASC) VISIBLE,
  INDEX `idrole_idx` (`idrole` ASC) VISIBLE,
  INDEX `idseniority_idx` (`idseniority` ASC) VISIBLE,
  CONSTRAINT `idteam`
    FOREIGN KEY (`idteam`)
    REFERENCES `Devathon`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idrole`
    FOREIGN KEY (`idrole`)
    REFERENCES `Devathon`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idseniority`
    FOREIGN KEY (`idseniority`)
    REFERENCES `Devathon`.`Seniority` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
